In [1]:
import numpy as np
from enum import Enum
from queue import Queue

In [2]:
grid = np.array([
    [0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0],
    [0, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 0, 0],
])

start = (1, 0)
goal = (4, 4)

In [3]:
class Action(Enum): 
    LEFT = (0, -1)
    RIGHT = (0, 1)
    UP = (-1, 0)
    DOWN = (1, 0)

    def __str__(self):
        if self == self.LEFT:
            return '<'
        elif self == self.RIGHT:
            return '>'
        elif self == self.UP:
            return '^'
        elif self == self.DOWN:
            return 'v'

In [4]:
# Reurns the valid moves depending on the current node
def valid(grid, current):
  valid = []
  for act in Action:
    delta = act.value
    next_pos = (current[0] + delta[0], current[1] + delta[1])

    is_inside_grid = (next_pos[0] >= 0 and next_pos[0] < len(grid)) and (next_pos[1] >= 0 and next_pos[1] < len(grid[0])) 
    
    if is_inside_grid and grid[next_pos] != 1:
      valid.append(act)
      
  return valid

In [5]:
# BREADTH FIRST SEARCH
def BFS(grid, start, goal):
    q = Queue()
    q.put(start)

    visited = set()
    visited.add(start)

    branch = {}

    i=0 
    while True:
        current = q.get()
        
        if current == goal:
            break

        for action in valid(grid, current):
            i+=1
            delta = action.value
            next_pos = (current[0] + delta[0], current[1] + delta[1])

            if next_pos not in visited:                
                visited.add(next_pos)                           # 1. Mark it as visited           
                q.put(next_pos)                                 # 2. Add it to the queue
                branch[next_pos] = (current, action)            # 3. Add how to get there to branch
    
    # Retrace path
    path = []
    n = goal
    while branch[n][0] != start:
        # append each new node to the path
        path.append(branch[n][1])
        n = branch[n][0]

    # append the start location
    path.append(branch[n][1])
    print(i)
    # reverse the path
    return path[::-1]

In [6]:
path = BFS(grid, start, goal)

55


In [7]:
# PRINT RESULT
print(grid)
for act in path:
    print(act, end=' ')

[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 1 0 0]
 [0 0 0 1 1 0]
 [0 0 0 1 0 0]]
v v > > ^ ^ > > > v v v < 